remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Juan José Botero Muriel
submodulo: Invesa
periodo: 2024
url_foto: https://firebasestorage.googleapis.com/v0/b/prueba-3738c.appspot.com/o/foto.jpg?alt=media&token=54dfe761-4d88-446c-8d7b-33620e91df5a&_gl=1*1lvs7mi*_ga*MzczMDg5NjQzLjE2OTYwODUyNTY.*_ga_CW55HF8NVT*MTY5NjA4NTI1Ny4xLjEuMTY5NjA4NTQ1Mi4xMS4wLjA.
# favicon: https://firebasestorage.googleapis.com/v0/b/prueba-3738c.appspot.com/o/foto.jpg?alt=media&token=54dfe761-4d88-446c-8d7b-33620e91df5a&_gl=1*1lvs7mi*_ga*MzczMDg5NjQzLjE2OTYwODUyNTY.*_ga_CW55HF8NVT*MTY5NjA4NTI1Ny4xLjEuMTY5NjA4NTQ1Mi4xMS4wLjA.
